### PR TITLE
Replace `ImageMode` API when running under qbicc

### PR DESCRIPTION
**Pull request by dmlloyd**
Depends on [quarkus #29993](https://github.com/quarkusio/quarkus/pull/29993).

### CODE REVIEW

**Comment by dgrove-oss** [comment]
When we merge this, let's get rid of https://github.com/qbicc/qbicc/pull/1650

**Comment by dmlloyd** [comment]
Quarkus 2.16 is [proposed](https://github.com/quarkusio/quarkus/wiki/Release-Planning#216-proposal) to be released on January 25th.

**Comment by dmlloyd** [comment]
This is ready for review now, since we're updated to 2.16.

**Review by dgrove-oss — APPROVED** [review]

**Comment by dgrove-oss** [comment]
Testing this.  We're not processing the patch.  I think the problem is that we need to get the quarkus-qbicc-runtime's jar file on the classpath of the application so the patcher will kick in

**Comment by dmlloyd** [comment]
The patcher might not function on the app class path because of the unimplemented resource methods on the corresponding ClassContext. I can look into that today.

**Pull request merged**
